---
# https://github.com/james-willett/mkdocs-material-youtube-tutorial
site_name: ${{ steps.repo_info.outputs.repo_name }}
site_description: ${{ steps.repo_info.outputs.repo_description }}
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
#  palette:
#    - scheme: default
#      toggle:
#        icon: material/toggle-switch-off-outline 
#        name: Switch to dark mode
#      primary: teal
#      accent: purple 
#    - scheme: slate 
#      toggle:
#        icon: material/toggle-switch
#        name: Switch to light mode    
#      primary: teal
#      accent: lime
nav:
  - Home: index.md
  - PRD: PRD.md
#  - FRD: FRD.md
#  - DRD: DRD.md
  - Code: docstrings.md
#  - Code: Code.md
#  - Configuration: pyproject.md
  - Change Log: CHANGELOG.md
  - License: LICENSE.md
#  - Third-Party Licenses: LICENSES.md
plugins:
#  - gen-files:
#      scripts: [scripts/gen_mkdocs_docstring_pages.py]
#  - literate-nav:
#      nav_file: Code.md
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          paths: [app]
          show_source: false
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
validation:
  links:
    not_found: warn
    anchors: warn
# builds only if validation succeeds while threating warnings as errors
# also checks for broken links
# poetry run mkdocs build --strict
strict: true
...
